### ISSUE TITLE
'Submit' button doesn't appear to do anything

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds-viewer#104]
As a user, I'd expect an acknowledgement of my action when hitting the 'submit' button - a message thanking me for submitting a task, a new playbill loaded, or both.

**Comment by alexandermendes** [comment]
I'm leaving it up to whatever client consumes this module to decide how to handle the task submissions, be that send them to an annotations server, store them in a database, etc. This way we can keep this module separate from any specific model. So, if you open up a console (under developer tools on Chrome etc.) you'll see the annotations emitted when submit is clicked.

So when we use this in the LibCrowds projects and that event is received we can store the data, remove the task from the queue and maybe show a notification like "Answer saved". I have added a "go to next on submit" option and will release a version update soon (should be today).

**Comment by alexandermendes** [comment]
Ah I should note that I'm talking about the [demo](https://libcrowds.github.io/libcrowds-viewer/) where you can see those events printed out!
