### ISSUE TITLE
Add option to view all tasks associated with the same target

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds-viewer#133]
Search the tasks loaded by `imgInfoUri`, then use this to display all regions available on a page for transcription. Users can click each highlighted region to be taken to that task (and shown the relevant transcription form).

So something like n titles highlighted in blue, as the user transcribes and clicks submit they turn green and automatically moves on to the next.

As the page could look very daunting with 100 regions marked up on a page we can also add a toggle to show/hide all other regions.

**Comment by alexandermendes** [comment]
If `disableComplete` is enabled then the user can only submit once. They are free to cycle back and forth between tasks/regions as much as they like but at some point we do need to submit/save. Regions will remain on the page but be shown highlighted in green.

![untitled](https://user-images.githubusercontent.com/5636273/28825940-14533688-76c0-11e7-9a20-1f82603b7a6f.png)

**Comment by alexandermendes** [comment]
@mialondon This is partly me thinking through the issue myself but does this sound about right?

**Comment by mialondon** [comment]
@alexandermendes sounds good to me! Is the first region highlighted on page load?

How do they move onto the next region - hit a 'next title/name' button until the final region when the option changes to 'submit page'?

**Comment by mialondon** [comment]
Highlighted areas should be linked to the data entry field through colour. Instructions say 'type in highlighted title and subtitle'.

**Comment by alexandermendes** [comment]
So I want to keep the tasks separate as I like the idea of having one finite task (e.g. transcribe the title), stored as one row in our database, linked to *n* answers, each being a row in a different table containing one annotation. We can easily compare these directly when it comes to checking if transcriptions match. As opposed to the other option where one task becomes transcribe 10 titles, all being stored in the same row, giving us a much harder time comparing the related answers - now each answer row contains 10 transcriptions and once we separate the matching from not matching ones, where do they go! I guess we have to create another set of tables and it all becomes a horrible mess. Just can't see it logically.

What we can do is add a `show-related-tasks` option which will search the task set, get all tasks that use the same image and add any related overlays to the image, making them clickable so that people have the option to click or scroll to other tasks on the same image but maintaining our single task/answer per row strategy.

**Comment by alexandermendes** [comment]
So hopefully we're coming to a nice compromise here. The demo now shows an example where `show-related-tasks` is enabled. I think it has the functionality we're after but the tasks actually remain separate. This does mean that the user has to click submit each time. We can consider adding a submit all button later. Users can already scroll back and forth between tasks using the < > buttons.
