### ISSUE TITLE
Add prompt 'are you sure you want to leave this page without saving your changes?' on moving forward to next item

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds-viewer#134]
Option to go back and save or abandon changes.

**Comment by alexandermendes** [comment]
`beforeunload` is really unreliable and difficult to get working across different browsers...

https://developers.google.com/web/updates/2017/03/dialogs-policy

Check out the [PageVisibility API](https://w3c.github.io/page-visibility)

**Comment by alexandermendes** [comment]
In essence, we also want to avoid showing a bunch of warning dialogues that get in the way of user actions. The client can use the message bus and the `taskchange` event to show a warning message if the previous task was not saved, but we shouldn't make the user click confirm every time they might want to browse away from a task before saving.

What we do need to fix is the confirm message before the page is unloaded entirely and therefore state would be lost.

**Comment by alexandermendes** [comment]
See also:

https://developer.mozilla.org/de/docs/Web/API/WindowEventHandlers/onbeforeunload

We might have to rethink this!

**Comment by alexandermendes** [comment]
This will cover as much as possible for now, but it probably won't be long before this event disappears completely!

**Comment by mialondon** [comment]
Removing the option to browse forward will help with this.
