### ISSUE TITLE
Add 'type ahead' that pulls previously typed values

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds-viewer#136]
NB we'll clean the data post-transcription to allow for differences in e.g. 'a musical farce' and 'musical farce'. The aim is to keep this a 'type what you see' task and not ask people to try to match it to a limited subset of potential genres.

**Comment by alexandermendes** [comment]
Let's use [`<datalist>`](https://developer.mozilla.org/en/docs/Web/HTML/Element/datalist) for this (go HTML5 😄 )

**Comment by alexandermendes** [comment]
Closing as this isn't really a viewer issue, it will be handled via the options passed to vue-form-generator.

**Comment by mialondon** [comment]
@alexandermendes I don't mind where the issue is recorded, but does that mean it's not on the To Do list anymore?

**Comment by alexandermendes** [comment]
So the easiest thing to do would be to build our list in https://github.com/LibCrowds/project-iiif-annotate, which can be updated periodically. I'll get to this before we're ready to launch the genre transcription task.
