### ISSUE TITLE
Images don't load on Firefox

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds-viewer#14]
Windows 7 (BL PC), Firefox 54.0.x

Screen at https://libcrowds.github.io/libcrowds-viewer/ shows this error message: Unable to open [object Object]: HTTP 0 attempting to load TileSource

![fireshot screen capture 536 - libcrowds viewer - libcrowds_github_io_libcrowds-viewer](https://user-images.githubusercontent.com/380763/28068248-90290e52-663c-11e7-8f3c-7ae7ca25cba5.png)

**Comment by alexandermendes** [comment]
Thanks, we're pretty much using [OpenSeadragon.Viewer.open](https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#open) directly to load the tile source so I'll have a look to see if there is anything that needs to be configured differently there

**Comment by mialondon** [comment]
I've tried at home (MacOS 10.12.4, Firefox 54.0.1) and on the work laptop (Windows 7, Firefox 54.0), so it's probably just my browser. We can re-open this if anyone else reports it.

**Comment by alexandermendes** [comment]
I think this was possibly something to do with our networks at the library. I just had the same thing when connected to BYOD that resolved itself as soon as I switched to Corporate. No time to investigate now but yeah, we can probably ignore it until it comes up elsewhere.
