### ISSUE TITLE
Copy image location icon URL should go to the UV page with associated metadata

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds-viewer#140]
The image by itself isn't as useful for researchers and doesn't allow us to share any necessary licensing etc information that's available on the UV page.

So the image e.g. https://api.bl.uk/image/iiif/ark:/81055/vdc_100022589091.0x000005/full/full/0/default.jpg should open in the item http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002 - ideally on the exact same image/page.

**Comment by alexandermendes** [comment]
I'm not sure if we have a way of linking to specific pages in the UV (using the image identifiers) but I'll check it out.

**Comment by irv** [comment]
You can currently specify the canvas index id, using the "cv" parameter, e.g. in mia's example:
http://access.bl.uk/item/viewer/ark:/81055/vdc_100022589092.0x000002#?cv=2

**Comment by alexandermendes** [comment]
Ah, interesting, thanks

**Comment by alexandermendes** [comment]
So the module isn't currently linked to the BL in any way. So, I'll have to figure out how to make this a config setting. Will get to it later!

**Comment by alexandermendes** [comment]
We'll handle this by simply generating the link outside the viewer and adding a property `shareUrl` or similar

**Comment by alexandermendes** [comment]
Covered in https://github.com/LibCrowds/libcrowds-viewer/pull/196

**Comment by mialondon** [comment]
@alexandermendes is there any way to add the canvas ID so that people can share specific images? At the moment there's no way for them to link to a particular playbill in forum discussions.

**Comment by mialondon** [comment]
Ah, there is, but it's only on the 'share' icon and not on the 'info' modal. While 'share' still writes over your buffer without warning I'm wary of suggesting that to people.

**Comment by alexandermendes** [comment]
@mialondon Two seperate points there. The data in the info modal comes directly from the manifest. I don't think we want to start messing around with that.

There is already a seperate issue open for the share button improvements.

**Comment by mialondon** [comment]
@alexandermendes ideally the info page would offer Link to this item; Link to this page.

**Comment by alexandermendes** [comment]
@mialondon So I'll cover it here: https://github.com/LibCrowds/vue-pybossa-frontend/issues/260. In general I think we should give preference to raising new issues rather than reopening old ones (e.g. in this case we have solved the original issue but are now talking about something quite different), might just be me but it gets a bit confusing!

**Comment by mialondon** [comment]
@alexandermendes my bad, adding a new issue when requesting the canvas ID is added to the share link!

**Comment by alexandermendes** [comment]
No probs, just trying to stop things getting out of control, a lot of issues to manage now!
