### ISSUE TITLE
Annotation should be at canvas not image level

### ISSUE THREAD

**Issue by irv** [LibCrowds/libcrowds-viewer#177]
e.g from http://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589092.0x000002/manifest.json

if the annotation was on the first image the target should not be on "http://api.bl.uk/image/iiif/ark:/81055/vdc_100022589091.0x000003/full/max/0/default.jpg", (or http://api.bl.uk/image/iiif/ark:/81055/vdc_100022589091.0x000003) but the canvas id of http://api.bl.uk/metadata/iiif/ark:/81055/vdc_100022589092.0x000163

which you can grab by finding the parent of the image info and using the "on" property

this would help with #140 eventually (but for now you can only use canvas index rather than id)

**Comment by alexandermendes** [comment]
Cool, actually only just found the v3 draft of the presentation API, so will cover this in https://github.com/LibCrowds/libcrowds-viewer/issues/178
