### ISSUE TITLE
Tweaks to Help text

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds-viewer#186]
A placeholder for findings during usability testing.

In the meantime:

- [x] Does 'select mode' still exist if there's no other mode?

- [x] The pan control icons need to be updated.

**Comment by alexandermendes** [comment]
Not sure about the first one - there are currently two modes - 'select' and 'transcribe' - and each task sent to the viewer has to be configured to use one of these.

The pan controls were updated here: https://github.com/LibCrowds/libcrowds-viewer/issues/143

**Comment by alexandermendes** [comment]
Oops, just got that you were referring specifically to the icons in the help modal and when the select mode help is shown. I'll fix these this eve.

**Comment by alexandermendes** [comment]
Pan icons updated, and no, there is no default for select mode. The help modal is configured to only show the select guidance if select mode is enabled.
