### ISSUE TITLE
Selection icons are pale on Firefox

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/libcrowds-viewer#81]
It's probably made worse by the laptop screen, but it's hard to instantly understand the tick and cross icons as they're quite pale on Firefox.

![pale_icons_ff](https://user-images.githubusercontent.com/380763/28464275-588175ba-6e1c-11e7-997b-e9f1a4421bc7.PNG)

**Comment by alexandermendes** [comment]
Ah yeah, didn't bother to fix it as we're dropping that selection plugin entirely as it was causing various other problems, so will have to restyle anyway.
