### ISSUE TITLE
Make purpose of selection box clearer

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds-viewer#96]
Options:

1. Hide until populated
2. Add a subtitle (and perhaps a question mark tooltip)

**Comment by alexandermendes** [comment]
On larger screens the sidebar can look a bit sparse without it (see screenshot) but when empty and the user first visits it isn't clear what it's there for.

![untitled](https://user-images.githubusercontent.com/5636273/28666343-d9821394-72be-11e7-8af6-3012814ffc82.png)

**Comment by mialondon** [comment]
I vote for option 1. 'Sparse' can also mean 'focused' :)
